-- Execute este script no SQL Editor do Supabase.
create table if not exists public.flights (
    id bigint generated by default as identity primary key,
    flight_number text not null,
    operator text not null,
    origin text not null,
    destination text not null,
    departure text not null,
    arrival text not null,
    status text not null default 'Programado',
    updated_at date not null default current_date,
    unique (flight_number, departure, origin, destination)
);

create index if not exists idx_flights_departure on public.flights (departure);
create index if not exists idx_flights_route on public.flights (origin, destination);

alter table public.flights enable row level security;

drop policy if exists "voos públicos podem ser lidos" on public.flights;
create policy "voos públicos podem ser lidos"
    on public.flights for select
    using (true);
